### ISSUE TITLE
Possibility to add custom stylings?

### ISSUE THREAD

**Issue by n19htz** [timtnleeProject/vuejs-clipper#15]
Hello, is there a way to add custom styles to elements, like corners etc?

**Comment by timtnleeProject** [comment]
Well, it's a little bit tricky, I have not figured out a better design for this.

## Using css to style child component

For example, you have an `example.vue` that has a child component `clipper-basic`

```html
<!--example.vue-->
<div>
  <clipper-basic class="basic"></clipper-basic>
</div>
```

You can check the [source code](https://github.com/timtnleeProject/vuejs-clipper/blob/master/src/components/clipper-basic.vue) or using dev tools like Chrome console to find the classes that affect elements' style.

For example, the corner style is defined like this
```scss
.zoom-area {
  //...
  & .corner {
    position: absolute;
    border-color: white;
    border-style: solid;
    width: 10px;
    height: 10px;
    opacity: 0.7;
  }
}
```

To override the child component's style, you need to make your css specificity greater than child component's. See [this article](https://medium.com/vuejs-tips/override-scoped-css-de4275119b87).

The origin corner's css specificity is  3: `.zoom-area .corner[data-xxx]` (It's using [vue-loader's scoped css](https://bambielli.com/til/2018-08-19-how-to-target-child-components-with-scoped-css-in-vue/#))

To override it in the parent component, your style rule's css specificity  must surpass 3, for examples:

```html
<style scoped>
/deep/.zoom-area .corner{
  border-color: black;
}
</style>
```
or

```html
<style>
.basic .zoom-area .corner{
  border-color: black;
}
</style>
```

There are many styled rules in the components that have high css specificity so it's not easy to make custom stylings.
